%% build_clean_foc_hardware.m
% Pristine build of FOC_Clean_Hardware.slx from VirtualSpeedDyno.slx

m = 'FOC_Clean_Hardware';
if bdIsLoaded(m), close_system(m, 0); end

% 1. Copy VirtualSpeedDyno
load_system('VirtualSpeedDyno');
save_system('VirtualSpeedDyno', m);

% 2. Hardware board and solver config
set_param(m, 'HardwareBoard', 'TI Piccolo F28069M LaunchPad');
set_param(m, 'SystemTargetFile', 'ert.tlc');
set_param(m, 'SolverType', 'Fixed-step');
set_param(m, 'Solver', 'FixedStepDiscrete');
set_param(m, 'FixedStep', '50e-6');
set_param(m, 'StopTime', 'inf');

% 3. SCI_A 115200 Baud
cs = getActiveConfigSet(m);
data = codertarget.data.getData(cs);
data.SCI_A.UserBaudRate = '115200';
data.SCI_A.BaudRate = 114796;
data.SCI_A.BaudRatePrescaler = 97;
codertarget.data.setData(cs, data);

% 4. Delete Simscape & simulation blocks
s_blks = find_system(m, 'SearchDepth', 1, 'BlockType', 'SimscapeBlock');
for i=1:length(s_blks), delete_block(s_blks{i}); end

extra = {'Solver Configuration', 'Gate Driver', 'PWM Generator', ...
         'PS-Simulink Converter', 'PS-Simulink Converter1', ...
         'PS-Simulink Converter2', 'PS-Simulink Converter3', ...
         'Simulink-PS Converter', 'Scope', 'Scope1', 'Scope2', ...
         'Scope3', 'Scope4', 'Scope5', 'i-Tracking', ...
         'Ideal Angular Velocity Source', 'Ideal Torque Sensor', ...
         'Ideal Rotational Motion Sensor'};
for i=1:length(extra)
    b = [m '/' extra{i}];
    if ~isempty(find_system(m, 'SearchDepth', 1, 'Name', extra{i}))
        delete_block(b);
    end
end

% 5. Copy verified hardware blocks from Official_Encoder_Calib_Site2
load_system('Official_Encoder_Calib_Site2');
add_block('Official_Encoder_Calib_Site2/Heartbeat LED', [m '/Heartbeat LED'], 'Position', [50 50 150 100]);
add_block('Official_Encoder_Calib_Site2/Offset Calculation/PWM Output', [m '/PWM Output'], 'Position', [1150 250 1300 350]);

% 6. Add Scale_to_PWM_Counts between Saturation and PWM Output
add_block('simulink/Math Operations/Gain', [m '/Scale_to_PWM_Counts'], ...
    'Gain', '2250', 'Position', [1050 260 1100 290]);

% Connect Saturation -> Scale_to_PWM_Counts -> PWM Output:1
add_line(m, 'Saturation/1', 'Scale_to_PWM_Counts/1');
add_line(m, 'Scale_to_PWM_Counts/1', 'PWM Output/1');

% 7. Add Feedback Subsystem
fb = [m '/Feedback'];
add_block('simulink/Ports & Subsystems/Subsystem', fb, 'Position', [50 200 200 380]);
% Delete default In1/Out1 in Feedback
delete_block([fb '/In1']); delete_block([fb '/Out1']);

% Copy ADC and eQEP into Feedback
add_block('Official_Encoder_Calib_Site2/Offset Calculation/IA//IB Measurement', [fb '/ADC'], 'Position', [50 50 180 100]);
add_block('Official_Encoder_Calib_Site2/Offset Calculation/eQEP', [fb '/eQEP'], 'Position', [50 150 180 200]);
set_param([fb '/eQEP'], 'useModule', 'eQEP1');
set_param([fb '/eQEP'], 'pcMaximumvalue', '4*1024 - 1');

% Add MATLAB Function Feedback_Processing
fn_block = sprintf('%s/Feedback_Processing', fb);
matlabFn = sprintf([...
    'function [i_abc, th_e, w_m, calib_done] = Feedback_Processing(adc_counts, raw_qep)\\n', ...
    '%%#codegen\\n', ...
    'persistent offset_u offset_v calib_count cal_complete prev_th_m w_m_flt\\n', ...
    'if isempty(calib_count)\\n', ...
    '    offset_u = single(2048.0);\\n', ...
    '    offset_v = single(2048.0);\\n', ...
    '    calib_count = single(0);\\n', ...
    '    cal_complete = false;\\n', ...
    '    prev_th_m = single(0);\\n', ...
    '    w_m_flt = single(0);\\n', ...
    'end\\n', ...
    'N_CALIB = single(10000);\\n', ...
    'u_meas = single(adc_counts(1));\\n', ...
    'v_meas = single(adc_counts(2));\\n', ...
    'if ~cal_complete\\n', ...
    '    if calib_count < N_CALIB\\n', ...
    '        calib_count = calib_count + single(1.0);\\n', ...
    '        offset_u = offset_u + (u_meas - offset_u) / calib_count;\\n', ...
    '        offset_v = offset_v + (v_meas - offset_v) / calib_count;\\n', ...
    '    else\\n', ...
    '        cal_complete = true;\\n', ...
    '    end\\n', ...
    'end\\n', ...
    'K_I = single(3.3 / (4095.0 * 0.012));\\n', ...
    'i_a = (u_meas - offset_u) * K_I;\\n', ...
    'i_b = (v_meas - offset_v) * K_I;\\n', ...
    'i_c = -(i_a + i_b);\\n', ...
    'i_abc = [i_a; i_b; i_c];\\n', ...
    'TWO_PI = single(6.283185307179586);\\n', ...
    'th_m = (single(raw_qep) / single(4096.0)) * TWO_PI;\\n', ...
    'TH_OFFSET = single(1.790708);\\n', ...
    'th_e_unmod = single(21.0) * th_m + TH_OFFSET;\\n', ...
    'th_e = mod(th_e_unmod, TWO_PI);\\n', ...
    'if th_e < single(0), th_e = th_e + TWO_PI; end\\n', ...
    'd_th = th_m - prev_th_m;\\n', ...
    'if d_th > single(3.14159265), d_th = d_th - TWO_PI;\\n', ...
    'elseif d_th < single(-3.14159265), d_th = d_th + TWO_PI; end\\n', ...
    'prev_th_m = th_m;\\n', ...
    'w_m_raw = d_th * single(20000.0);\\n', ...
    'ALPHA = single(0.03);\\n', ...
    'w_m_flt = w_m_flt + ALPHA * (w_m_raw - w_m_flt);\\n', ...
    'w_m = w_m_flt;\\n', ...
    'calib_done = single(cal_complete);\\n']);

% Add MATLAB Function to Feedback
add_block('simulink/User-Defined Functions/MATLAB Function', fn_block, 'Position', [260 80 400 200]);
sf = sfroot;
ch = sf.find('Path', fn_block, '-isa', 'Stateflow.EMChart');
ch.Script = matlabFn;

% Add Outports to Feedback
add_block('simulink/Sinks/Out1', [fb '/i_abc'], 'Position', [480 85 510 100]);
add_block('simulink/Sinks/Out1', [fb '/th_e'], 'Position', [480 115 510 130]);
add_block('simulink/Sinks/Out1', [fb '/w_m'], 'Position', [480 145 510 160]);
add_block('simulink/Sinks/Out1', [fb '/calib_done'], 'Position', [480 175 510 190]);

% Wire inside Feedback
add_line(fb, 'ADC/1', 'Feedback_Processing/1');
add_line(fb, 'eQEP/1', 'Feedback_Processing/2');
add_line(fb, 'Feedback_Processing/1', 'i_abc/1');
add_line(fb, 'Feedback_Processing/2', 'th_e/1');
add_line(fb, 'Feedback_Processing/3', 'w_m/1');
add_line(fb, 'Feedback_Processing/4', 'calib_done/1');

% 8. Add Gotos in main model for Feedback outputs
add_block('simulink/Signal Routing/Goto', [m '/Goto_i_abc'], 'GotoTag', 'i_abc', 'Position', [250 205 320 225]);
add_block('simulink/Signal Routing/Goto', [m '/Goto_th_e'], 'GotoTag', 'th_e', 'Position', [250 245 320 265]);
add_block('simulink/Signal Routing/Goto', [m '/Goto_w_m'], 'GotoTag', 'w_m', 'Position', [250 285 320 305]);

add_line(m, 'Feedback/1', 'Goto_i_abc/1');
add_line(m, 'Feedback/2', 'Goto_th_e/1');
add_line(m, 'Feedback/3', 'Goto_w_m/1');

% 9. Add Command Subsystem (SCI Receive)
cmd_sys = [m '/Command'];
add_block('simulink/Ports & Subsystems/Subsystem', cmd_sys, 'Position', [50 420 200 520]);
delete_block([cmd_sys '/In1']); delete_block([cmd_sys '/Out1']);
add_block('Official_Encoder_Calib_Site2/Serial Receive/SCI Receive', [cmd_sys '/SCI_Rx'], 'Position', [50 50 160 100]);
set_param([cmd_sys '/SCI_Rx'], 'sciModule', 'A', 'dataType', 'uint8', 'dataDim', '1');

% Add Command Decoder MATLAB Function
cmd_fn = sprintf('%s/Decode_Command', cmd_sys);
cmd_matlab = sprintf([...
    'function [w_ref, run_cmd] = Decode_Command(rx_byte, calib_done)\\n', ...
    '%%#codegen\\n', ...
    'persistent run_state target_w\\n', ...
    'if isempty(run_state)\\n', ...
    '    run_state = single(0);\\n', ...
    '    target_w  = single(0);\\n', ...
    'end\\n', ...
    'byte = uint8(rx_byte);\\n', ...
    'if byte == uint8(49) || byte == uint8(1)\\n', ...
    '    run_state = single(1);\\n', ...
    '    target_w  = single(10.4719755); %% 100 RPM\\n', ...
    'elseif byte == uint8(50) || byte == uint8(2)\\n', ...
    '    run_state = single(1);\\n', ...
    '    target_w  = single(20.943951);  %% 200 RPM\\n', ...
    'elseif byte == uint8(48) || byte == uint8(0)\\n', ...
    '    run_state = single(0);\\n', ...
    '    target_w  = single(0);\\n', ...
    'end\\n', ...
    'if calib_done < single(0.5)\\n', ...
    '    run_cmd = single(0);\\n', ...
    '    w_ref   = single(0);\\n', ...
    'else\\n', ...
    '    run_cmd = run_state;\\n', ...
    '    w_ref   = target_w;\\n', ...
    'end\\n']);

add_block('simulink/User-Defined Functions/MATLAB Function', cmd_fn, 'Position', [220 50 360 140]);
ch2 = sf.find('Path', cmd_fn, '-isa', 'Stateflow.EMChart');
ch2.Script = cmd_matlab;

add_block('simulink/Sources/In1', [cmd_sys '/calib_done'], 'Position', [50 120 80 135]);
add_block('simulink/Sinks/Out1', [cmd_sys '/w_ref'], 'Position', [420 60 450 75]);
add_block('simulink/Sinks/Out1', [cmd_sys '/run_cmd'], 'Position', [420 100 450 115]);

add_line(cmd_sys, 'SCI_Rx/1', 'Decode_Command/1');
add_line(cmd_sys, 'calib_done/1', 'Decode_Command/2');
add_line(cmd_sys, 'Decode_Command/1', 'w_ref/1');
add_line(cmd_sys, 'Decode_Command/2', 'run_cmd/1');

% Connect calib_done from Feedback to Command
add_line(m, 'Feedback/4', 'Command/1');

% Connect Command/2 (run_cmd) to PWM Output/2 (EnPWM)
add_line(m, 'Command/2', 'PWM Output/2');

% 10. Speed Control & Current Clamp (Iq_max = 2.5 A)
% In VirtualSpeedDyno, Subtract5 = w_ref - w_m
% Replace Constant6 with Command/1 (w_ref)
h_sub5 = get_param([m '/Subtract5'], 'PortHandles');
l_sub5 = get_param(h_sub5.Inport(1), 'Line');
if l_sub5 ~= -1, delete_line(l_sub5); end
if ~isempty(find_system(m, 'SearchDepth', 1, 'Name', 'Constant6')), delete_block([m '/Constant6']); end
add_line(m, 'Command/1', 'Subtract5/1');

% Replace From15 input with w_m
set_param([m '/From15'], 'GotoTag', 'w_m');

% Add Iq Clamp Saturation block
add_block('simulink/Discontinuities/Saturation', [m '/Iq_Clamp'], ...
    'UpperLimit', '2.5', 'LowerLimit', '-2.5', ...
    'Position', [450 350 490 380]);
add_line(m, 'PID Controller2/1', 'Iq_Clamp/1');

% Feed Iq_Clamp into Subtract1:1 (replacing open-loop Gain/i_q_ref)
% Delete old line to Subtract1:1
h_sub1 = get_param([m '/Subtract1'], 'PortHandles');
l_sub1 = get_param(h_sub1.Inport(1), 'Line');
if l_sub1 ~= -1, delete_line(l_sub1); end
add_line(m, 'Iq_Clamp/1', 'Subtract1/1');

save_system(m);
fprintf('FOC_Clean_Hardware model assembled and saved!\n');
