% -------------------------------------------------------------------------
% 96V GaN Motor Parameter Synthesizer - Real MuJoCo Data
% -------------------------------------------------------------------------
% This script mathematically synthesizes the optimal motor parameters
% based on the EXACT joint torque and velocity data extracted from the
% MuJoCo dynamic jump simulation.
% -------------------------------------------------------------------------

clear; clc; close all;

%% 1. Input Parameters

% Electrical & Thermal Assumptions
V_bus = 96.0;               % DC Bus Voltage [V]
P_thermal = 150.0;          % Max allowable continuous thermal dissipation [W]

% Drivetrain Assumptions
N = 10;                     % Fixed Gear Ratio (10:1)
eta_gear = 0.90;            % Gearbox efficiency

%% 2. Load Real MuJoCo Gait Data
% Load the CSV generated by test_kbot_legs.py
csv_file = '..\phase0\gait_data\jump_gait_data_legs.csv';
if ~isfile(csv_file)
    error('Could not find the MuJoCo data CSV at: %s', csv_file);
end

data = readtable(csv_file);

t = data.time;
% We will optimize for the Left Ankle joint requirements
w_joint = data.left_ankle_velocity;
T_joint = data.left_ankle_net_torque;

% Strip out the first 0.1s to ignore any initialization physics spikes
valid_idx = t > 0.1;
t = t(valid_idx);
w_joint = w_joint(valid_idx);
T_joint = T_joint(valid_idx);

% Calculate global maxima for the joint from the simulation
T_joint_peak = max(abs(T_joint));
T_joint_rms  = sqrt(mean(T_joint.^2));
w_joint_peak = max(abs(w_joint));

fprintf('--- MuJoCo Jump Requirements (Left Ankle) ---\n');
fprintf('Peak Joint Torque: %.1f Nm\n', T_joint_peak);
fprintf('RMS Joint Torque:  %.1f Nm\n', T_joint_rms);
fprintf('Peak Joint Speed:  %.1f rad/s\n\n', w_joint_peak);

% Reflect joint requirements to the bare motor
T_m = T_joint / (N * eta_gear);
w_m = w_joint * N;
T_m_peak = T_joint_peak / (N * eta_gear);
T_m_rms  = T_joint_rms / (N * eta_gear);
w_m_peak = w_joint_peak * N;

fprintf('--- Bare Motor Loading (Gear Ratio 10:1) ---\n');
fprintf('Peak Motor Torque Demand: %.2f Nm\n', T_m_peak);
fprintf('RMS Motor Torque Demand:  %.2f Nm\n', T_m_rms);
if T_m_rms <= 5.0
    fprintf('THERMAL CHECK: PASS (RMS %.2f Nm is under 5.0 Nm continuous rating)\n', T_m_rms);
else
    fprintf('THERMAL CHECK: FAIL (RMS %.2f Nm exceeds 5.0 Nm continuous rating!)\n', T_m_rms);
end
fprintf('\n');

%% 3. Synthesize the Optimal Motor
% Analytical Intersection of Thermal and Voltage Limits
numerator = V_bus / T_m_peak;
denominator = (P_thermal / T_m_rms^2) + (w_m_peak / T_m_peak);

Kt_opt = numerator / denominator;
R_opt  = P_thermal * (Kt_opt / T_m_rms)^2;
Km_opt = Kt_opt / sqrt(R_opt);

fprintf('--- Synthesized Optimal Motor (96V, %dW, GR 10:1) ---\n', P_thermal);
fprintf('Kt: %.3f Nm/A\n', Kt_opt);
fprintf('Kv: %.1f RPM/V\n', 9.5493/Kt_opt);
fprintf('R:  %.3f Ohms\n', R_opt);
fprintf('Km: %.3f Nm/sqrt(W)\n', Km_opt);

%% 4. Define Sub-Optimal Motors (Rewound with different turns, same mass/Km)
% Sub-optimal A: "High-Turns" (1.5x Kt) -> Wound for high torque
Kt_high = Kt_opt * 1.5;
R_high  = R_opt * (1.5)^2;

% Sub-optimal B: "Low-Turns" (0.6x Kt) -> Wound for high speed
Kt_low = Kt_opt * 0.6;
R_low  = R_opt * (0.6)^2;

%% 5. Evaluate Trajectories for all 3 motors

% A. Required Bus Voltage: V = I*R + Kt*w = (T/Kt)*R + Kt*w
V_req_opt  = abs(T_m / Kt_opt)  * R_opt  + Kt_opt  * abs(w_m);
V_req_high = abs(T_m / Kt_high) * R_high + Kt_high * abs(w_m);
V_req_low  = abs(T_m / Kt_low)  * R_low  + Kt_low  * abs(w_m);

% B. Instantaneous Thermal Dissipation: P = I^2 * R = (T/Kt)^2 * R
P_diss_opt  = (T_m / Kt_opt).^2  * R_opt;
P_diss_high = (T_m / Kt_high).^2 * R_high;
P_diss_low  = (T_m / Kt_low).^2  * R_low;

% Average Dissipation (RMS heat)
P_avg_opt  = mean(P_diss_opt);
P_avg_high = mean(P_diss_high);
P_avg_low  = mean(P_diss_low);

% C. Mechanical Power (Regen capability)
P_mech = T_m .* w_m;  % Negative indicates regenerative braking!

%% 6. Generate Thesis Plots

set(0, 'DefaultAxesFontSize', 12, 'DefaultLineLineWidth', 2);

% --- Figure 1: The Torque-Speed Operating Envelope ---
figure('Name', 'Operating Envelope', 'Position', [100, 100, 700, 600]);

w_plot = linspace(0, w_m_peak * 1.2, 100);

% T_max boundary curves: T = (V_bus - Kt*w) * (Kt / R)
T_max_opt  = (V_bus - Kt_opt .* w_plot)  .* (Kt_opt / R_opt);
T_max_high = (V_bus - Kt_high .* w_plot) .* (Kt_high / R_high);
T_max_low  = (V_bus - Kt_low .* w_plot)  .* (Kt_low / R_low);

plot(w_plot, T_max_opt, 'g', 'DisplayName', 'Optimal Motor Envelope'); hold on;
plot(w_plot, T_max_high, 'b--', 'DisplayName', 'High-Turns Motor (Voltage Choked)');
plot(w_plot, T_max_low, 'r--', 'DisplayName', 'Low-Turns Motor');

% Overlay the actual gait profile points from MuJoCo
scatter(abs(w_m), abs(T_m), 15, 'k', 'filled', 'DisplayName', 'MuJoCo Jump Knee Profile');

% Formatting
grid on;
ylim([0, T_m_peak * 1.5]);
xlim([0, w_m_peak * 1.5]);
xlabel('Motor Speed \omega (rad/s)');
ylabel('Motor Torque T (Nm)');
title(sprintf('Torque-Speed Capability vs Real Jump Data (96V, GR=%d:1)', N));
legend('Location', 'NorthEast');


% --- Figure 2: Time-Series Performance ---
figure('Name', 'Time Series Performance', 'Position', [150, 150, 1000, 900]);

% Subplot 1: The MuJoCo Gait Profile (Torque & Speed)
subplot(4,1,1);
yyaxis left;
plot(t, T_m, 'k'); ylabel('Torque (Nm)');
yyaxis right;
plot(t, w_m, 'k--'); ylabel('Speed (rad/s)');
title('Left Ankle Joint Profile (Extracted from MuJoCo Jump)');
grid on;

% Subplot 2: Mechanical Power (Regen)
subplot(4,1,2);
plot(t, P_mech, 'm', 'DisplayName', 'Mechanical Power'); hold on;
yline(0, 'k-', 'LineWidth', 1);
fill([t(1) t(end) t(end) t(1)], [-max(abs(P_mech)) -max(abs(P_mech)) 0 0], 'g', 'FaceAlpha', 0.1, 'EdgeColor', 'none', 'DisplayName', 'Regen Zone');
ylabel('Mech. Power (W)');
title('Regenerative Braking Capability');
legend('Location', 'NorthWest');
grid on;

% Subplot 3: Voltage Requirement (Saturation Risk)
subplot(4,1,3);
plot(t, V_req_opt, 'g', 'DisplayName', 'Optimal Motor'); hold on;
plot(t, V_req_high, 'b', 'DisplayName', 'High-Turns Motor');
plot(t, V_req_low, 'r', 'DisplayName', 'Low-Turns Motor');
yline(V_bus, 'k--', '96V Ceiling', 'LineWidth', 2, 'LabelHorizontalAlignment', 'left');
ylabel('Required Voltage (V)');
title('Voltage Demand over Time');
legend('Location', 'NorthWest');
grid on;

% Subplot 4: Thermal Dissipation (Overheating Risk)
subplot(4,1,4);
plot(t, P_diss_opt, 'g', 'DisplayName', sprintf('Optimal (Avg = %d W)', round(P_avg_opt))); hold on;
plot(t, P_diss_high, 'b', 'DisplayName', sprintf('High-Turns (Avg = %d W)', round(P_avg_high)));
plot(t, P_diss_low, 'r', 'DisplayName', sprintf('Low-Turns (Avg = %d W)', round(P_avg_low)));
yline(P_thermal, 'k--', 'Thermal Limit', 'LineWidth', 2, 'LabelHorizontalAlignment', 'left');
ylabel('Power Dissipated (W)');
xlabel('Time (s)');
title('Heat Generation over Time');
legend('Location', 'NorthWest');
grid on;

disp('MATLAB Analysis with Real MuJoCo Data Completed Successfully.');
