function cfg = F280049C_Hardware_Map_Test_Config()
%F280049C_HARDWARE_MAP_TEST_CONFIG Site-2 bring-up map for the F280049C.
%
% This is intentionally a peripheral-only configuration. It is not an FOC
% controller and it does not enable the EPC91200 gate driver. The companion
% model F280049C_Hardware_Map_Tests.slx contains one subsystem per
% peripheral so the maps can be built and checked independently.
%
% Usage:
%   cfg = F280049C_Hardware_Map_Test_Config();
%   F280049C_Hardware_Map_Test_Select('PWM');

root = fileparts(mfilename('fullpath'));

cfg.model = fullfile(root, 'F280049C_Hardware_Map_Tests.slx');
cfg.board = 'TI Piccolo F280049C LaunchPad';
cfg.clock_hz = 100e6;
cfg.pwm_frequency_hz = 20e3;
cfg.sample_time_s = 50e-6;
cfg.pwm_counter_period = 2500;

cfg.pwm = struct( ...
    'phaseU', struct('module', 'ePWM1', 'gpioHigh', 0, 'gpioLow', 1, ...
                     'adapterPins', 'J2-1/J2-3', 'duty_percent', 25), ...
    'phaseV', struct('module', 'ePWM4', 'gpioHigh', 6, 'gpioLow', 7, ...
                     'adapterPins', 'J2-5/J2-7', 'duty_percent', 50), ...
    'phaseW', struct('module', 'ePWM2', 'gpioHigh', 2, 'gpioLow', 3, ...
                     'adapterPins', 'J2-9/J2-11', 'duty_percent', 75));

cfg.adc = struct( ...
    'vbus', struct('module', 'A', 'soc', 0, 'channel', 'ADCINA6', ...
                   'adapterPin', 'J1-6/J7-63'), ...
    'ic', struct('module', 'B', 'soc', 0, 'channel', 'ADCINB6', ...
                 'adapterPin', 'J1-18/J7-64'), ...
    'ib', struct('module', 'C', 'soc', 1, 'channel', 'ADCINC14', ...
                 'adapterPin', 'J1-16/J7-65'), ...
    'ia', struct('module', 'C', 'soc', 0, 'channel', 'ADCINC1', ...
                 'adapterPin', 'J1-14/J7-66'), ...
    'trigger', 'ePWM1_SOCA', 'acquisition_window_cycles', 15, ...
    'resolution_bits', 12);

cfg.qep = struct('module', 'eQEP1', 'gpioA', 35, 'gpioB', 37, ...
                 'gpioIndex', 59, 'adapterPins', 'LAUNCHXL J12 A/B/I', ...
                 'decode', '2x', 'counter_max', '2^16-1', ...
                 'index_edge', 'Falling edge', ...
                 'reset_mode', 'Reset on the first index event');

cfg.spi = struct('module', 'SPI-B', 'gpioClock', 22, 'gpioMosi', 24, ...
                 'gpioMiso', 31, 'gpioChipSelect', 27, ...
                 'sensor', 'AS5047P', 'mode', 1, 'clock_hz', 1e6, ...
                 'bits', 16, 'bit_order', 'MSB first', ...
                 'angle_read_command_hex', 'FFFF');

cfg.sci = struct('module', 'SCI-A', 'rx_type', 'uint16', ...
                 'rx_length', 1, 'rx_timeout_s', 0.0175, ...
                 'baud_hz', 1.5e6, 'format', '8-N-1 little endian', ...
                 'baud_note', 'Matches the imported F280049C host offset example; verify the board COM driver accepts it');

cfg.gpio = struct('gate_enable_gpio', 34, ...
                  'gate_disable_level', true, ...
                  'ocp_gpio', 59, ...
                  'ocp_route', 'ePWM trip-zone TZ2 / GPTRIP2SEL');

cfg.safety = struct( ...
    'bus_voltage_first_test_V', 0, ...
    'gate_driver_enabled_at_startup', false, ...
    'motor_connected_for_first_test', false, ...
    'note', 'Keep nEN high and use a current-limited low-voltage bus until every map is verified.');

if nargout == 0
    fprintf('F280049C Site-2 map loaded for %s\n', cfg.board);
    fprintf('PWM: %g Hz, TBPRD=%d, Ts=%g s\n', ...
        cfg.pwm_frequency_hz, cfg.pwm_counter_period, cfg.sample_time_s);
    fprintf('Gate disable: GPIO%d = %d; OCPn route: GPIO%d through %s\n', ...
        cfg.gpio.gate_enable_gpio, cfg.gpio.gate_disable_level, ...
        cfg.gpio.ocp_gpio, cfg.gpio.ocp_route);
end
end
