function report = F280049C_Hardware_Map_Test_Validate()
%F280049C_HARDWARE_MAP_TEST_VALIDATE Check the saved 49C Site-2 model map.
%
% This is a static parameter audit. It does not flash the target or apply
% bus power. A passing result means the model contains the expected 49C
% peripheral selections; it does not prove adapter continuity or polarity.

cfg = F280049C_Hardware_Map_Test_Config();
if ~isfile(cfg.model)
    error('F280049C:MissingModel', 'Model not found: %s', cfg.model);
end

[~, modelName] = fileparts(cfg.model);
if ~bdIsLoaded(modelName)
    open_system(cfg.model);
end

checks = {};
check = @(condition, text) assert(condition, 'F280049C:MapMismatch', '%s', text);

check(strcmp(get_param(modelName, 'HardwareBoard'), cfg.board), ...
    'HardwareBoard is not TI Piccolo F280049C LaunchPad.');
check(strcmp(get_param(modelName, 'FixedStep'), '5e-5'), ...
    'FixedStep is not 50 us.');
checks{end+1} = 'board and fixed-step timing';

pwm1 = findOne(modelName, 'ePWM1');
pwm4 = findOne(modelName, 'ePWM4');
pwm2 = findOne(modelName, 'ePWM2');
check(strcmp(get_param(pwm1, 'useModule'), 'ePWM1') && ...
      strcmp(get_param(pwm4, 'useModule'), 'ePWM4') && ...
      strcmp(get_param(pwm2, 'useModule'), 'ePWM2'), ...
    'PWM modules are not ePWM1/ePWM4/ePWM2.');
for block = {pwm1, pwm4, pwm2}
    check(strcmp(get_param(block{1}, 'timerPeriod_clk'), '2500'), ...
        'A PWM block does not use TBPRD=2500.');
    check(strcmp(get_param(block{1}, 'ePWMxBStatus'), 'on') && ...
          strcmp(get_param(block{1}, 'DBpolarity'), 'Active high complementary (AHC)') && ...
          strcmp(get_param(block{1}, 'REDperiod'), '5') && ...
          strcmp(get_param(block{1}, 'FEDperiod'), '5'), ...
        'A PWM block is not configured for complementary A/B outputs with 5-cycle dead time.');
end
check(strcmp(get_param(pwm1, 'zeroSyncOut'), 'on'), ...
    'ePWM1 zero-event synchronization output is not enabled.');
check(strcmp(get_param(pwm1, 'adcstartModuleA'), 'on') && ...
      strcmp(get_param(pwm1, 'adcstartEventA'), 'Counter equals to period (CTR=PRD)'), ...
    'ePWM1 SOCA is not configured at CTR=PRD.');
checks{end+1} = 'PWM modules, period, synchronization, and SOCA';

adcA = findOne(modelName, 'ADCA_SOC0_ADCINA6_Vbus');
adcB = findOne(modelName, 'ADCB_SOC0_ADCINB6_Ic');
adcC1 = findOne(modelName, 'ADCC_SOC0_ADCINC1_Ia');
adcC14 = findOne(modelName, 'ADCC_SOC1_ADCINC14_Ib');
check(strcmp(get_param(adcA, 'ADCModule'), 'A') && strcmp(get_param(adcA, 'conv1_Type4'), 'ADCIN6'), ...
    'ADCA SOC0 is not ADCINA6.');
check(strcmp(get_param(adcB, 'ADCModule'), 'B') && strcmp(get_param(adcB, 'conv1_Type4'), 'ADCIN6'), ...
    'ADCB SOC0 is not ADCINB6.');
check(strcmp(get_param(adcC1, 'ADCModule'), 'C') && strcmp(get_param(adcC1, 'useSOC1'), 'SOC0') && ...
      strcmp(get_param(adcC1, 'conv1_Type4'), 'ADCIN1'), ...
    'ADCC SOC0 is not ADCINC1.');
check(strcmp(get_param(adcC14, 'ADCModule'), 'C') && strcmp(get_param(adcC14, 'useSOC1'), 'SOC1') && ...
      strcmp(get_param(adcC14, 'conv1_Type4'), 'ADCIN14'), ...
    'ADCC SOC1 is not ADCINC14.');
for block = {adcA, adcB, adcC1, adcC14}
    check(strcmp(get_param(block{1}, 'SOCTriggerSource'), 'ePWM1_ADCSOCA'), ...
        'An ADC SOC is not triggered by ePWM1_SOCA.');
end
checks{end+1} = 'ADC A/B/C channels, SOCs, and trigger';

qep = findOne(modelName, 'eQEP1_TI_J12');
check(strcmp(get_param(qep, 'useModule'), 'eQEP1') && ...
      strcmp(get_param(qep, 'externalClockrate'), '2x resolution: Count the rising/falling edge') && ...
      strcmp(get_param(qep, 'pcResetmode'), 'Reset on the first index event'), ...
    'eQEP1 is not configured for 2x first-index reset.');
checks{end+1} = 'eQEP1 count and index settings';

spi = findOne(modelName, 'SPIB_AS5047P_Mode1');
check(strcmp(get_param(spi, 'SPISelect'), 'SPI_B') && ...
      strcmp(get_param(spi, 'ClockMode'), '1') && ...
      strcmp(get_param(spi, 'DataBits'), '16') && ...
      strcmp(get_param(spi, 'FirstBitToTransfer'), 'Most significant bit (MSB)'), ...
    'SPI-B is not configured for AS5047P 16-bit mode 1.');
checks{end+1} = 'SPI-B AS5047P frame settings';

sciRx = findOne(modelName, 'SCI_A_Receive');
check(strcmp(get_param(sciRx, 'sciModule'), 'A'), ...
    'SCI-A is not selected for command RX.');
check(strcmp(get_param(sciRx, 'dataDim'), '4') && ...
      strcmp(get_param(sciRx, 'maxDataLength'), '4') && ...
      strcmp(get_param(sciRx, 'dataType'), 'uint16'), ...
    'SCI-A command receiver is not configured for four uint16 words.');
checks{end+1} = 'SCI-A receive/transmit settings';

telemetry = findOne(modelName, 'SCI_A_Telemetry');
telemetryHold = findOne(modelName, 'Telemetry_1ms');
check(strcmp(get_param(telemetry, 'sciModule'), 'A') && ...
      strcmp(get_param(telemetry, 'frameSize'), '3') && ...
      strcmp(get_param(telemetryHold, 'SampleTime'), '0.001'), ...
    'SCI-A telemetry is not a three-word 1 ms frame.');
checks{end+1} = 'QEP/SPI telemetry frame';

gpio = findOne(modelName, 'GPIO34_nEN');
check(strcmp(get_param(gpio, 'GPIO_Number'), 'GPIO32~GPIO34') && ...
      strcmp(get_param(gpio, 'GPIO_Bit2'), 'on'), ...
    'GPIO34 nEN output is not selected.');
checks{end+1} = 'GPIO34 safe nEN output';

report = struct('passed', true, 'model', cfg.model, 'checks', {checks});
fprintf('PASS: %d F280049C hardware-map checks\n', numel(checks));
end

function block = findOne(modelName, name)
blocks = find_system(modelName, 'LookUnderMasks', 'all', ...
    'FollowLinks', 'on', 'Name', name);
if numel(blocks) ~= 1
    error('F280049C:ModelStructure', ...
        'Expected one block named %s; found %d.', name, numel(blocks));
end
block = blocks{1};
end
